import { type ECSStatsType, EntityManager, type Plugin, type PluginConstructor, type System } from '~/core'
import { WorldEvent } from '~/definitions'
import { Clock } from '~/utils/clock'
import { log } from '~/utils/log'

type SystemStatsType = {
    /** Provided system label */
    label: string
    /** How long it took to run the system last frame (ms) */
    runtime: number
    /** Exta debug information provided by the system */
    extra: Record<string, string | number | boolean>
}

type SystemWrapper = {
    key: string
    priority: number
    system: System
}

export type StatsType = {
    /** Stats generated by the ECS */
    ecs: ECSStatsType
    /** Number of registered systems */
    systems: number
    /** Number of registered plugins */
    plugins: number
    /** Array of last frame system stats */
    systemsStats: Record<string, SystemStatsType>
}

export class World {
    private plugins = new Map<Plugin['constructor'], Plugin>()
    private observers: Record<WorldEvent, (() => void)[]> = {
        start: [],
        stop: [],
        endframe: [],
    }

    readonly stats: StatsType
    readonly ecs: EntityManager // TODO deprecate
    readonly entities: EntityManager
    readonly time: Clock

    systems: SystemWrapper[] = []

    // State
    isRunning = false

    // Settings
    frameSync = true

    constructor() {
        this.entities = new EntityManager()
        this.ecs = this.entities
        this.time = new Clock()

        this.stats = {
            ecs: this.ecs.stats,
            systems: 0,
            plugins: 0,
            systemsStats: {},
        }

        log.i('Gengine started')
    }

    /** Time elapsed since last frame in seconds */
    get timeElapsedS() {
        return this.time.delta
    }

    private tick = () => {
        if (this.isRunning) {
            if (this.frameSync) {
                requestAnimationFrame(this.tick)
            } else {
                setTimeout(this.tick)
            }
        }

        this.time.startFrame()

        for (const systemWrapper of this.systems) {
            const systemStart = Clock.now()
            systemWrapper.system(this)
            this.stats.systemsStats[systemWrapper.key].runtime = Math.ceil(Clock.now() - systemStart)
        }

        this.entities.flush()

        this.updateListeners('endframe')

        this.time.endFrame()
    }

    start() {
        if (!this.isRunning) {
            this.isRunning = true
            this.updateListeners('start')
            this.tick()
        }
    }

    stop() {
        if (this.isRunning) {
            this.isRunning = false
            this.updateListeners('stop')
        }
    }

    step() {
        if (!this.isRunning) {
            this.tick()
        }
    }

    addEventListener(eventName: WorldEvent, callback: () => void) {
        this.observers[eventName].push(callback)
    }

    removeEventListener(eventName: WorldEvent, callback: () => void) {
        const observers = this.observers[eventName]
        this.observers[eventName] = observers.filter((c) => c !== callback)
    }

    private updateListeners(eventName: WorldEvent) {
        for (const callback of this.observers[eventName]) {
            callback()
        }
    }

    private sortSystems() {
        this.systems.sort((a, b) => {
            if (a.priority < 0 || b.priority < 0) {
                // If one of the priorities is negative, reverse the logic (-1 means no priority)
                return b.priority - a.priority
            }
            // Simple sort in reverse order (0 is top priority)
            return a.priority - b.priority
        })
    }

    registerSystem(system: System, priority: number = -1) {
        this.systems.push({
            key: system.label,
            priority,
            system,
        })

        this.sortSystems()

        this.stats.systems = this.systems.length
        this.stats.systemsStats[system.label] = {
            label: system.label,
            runtime: 0,
            extra: {},
        }

        return this
    }

    registerSystems(systems: System[]) {
        systems.forEach((s) => this.registerSystem(s))

        return this
    }

    registerPlugin(plugin: Plugin) {
        this.plugins.set(plugin.constructor, plugin)

        this.stats.plugins = this.plugins.size

        plugin.init(this)

        return this
    }

    getPlugin<T extends Plugin>(pluginConstructor: PluginConstructor<T>) {
        return this.plugins.get(pluginConstructor) as T
    }
}
