import {
    EntityManager,
    type ECSStatsType,
    type System,
    type Plugin,
    type PluginCreator,
    type PluginFromPluginCreator,
} from 'core'

import { WorldEvent } from 'definitions'
import { log } from 'utils/log'
import { Clock } from 'utils/clock'

type SystemStatsType = {
    /** Provided system label */
    label: string
    /** How long it took to run the system last frame (ms) */
    runtime: number
    /** Exta debug information provided by the system */
    extra: Record<string, string | number | boolean>
}

export type StatsType = {
    /** Stats generated by the ECS */
    ecs: ECSStatsType
    /** Number of registered systems */
    systems: number
    /** Number of registered plugins */
    plugins: number
    /** Array of last frame system stats */
    systemsStats: Record<string, SystemStatsType>
}

export class World {
    private plugins = new Map<PluginCreator['label'], Plugin>()
    private systems: System[] = []
    private observers: Record<WorldEvent, (() => void)[]> = {
        start: [],
        stop: [],
        endframe: [],
    }

    readonly stats: StatsType
    readonly ecs: EntityManager
    readonly time: Clock

    // State
    isRunning = false

    // Settings
    frameSync = true

    constructor() {
        this.ecs = new EntityManager()
        this.time = new Clock()

        this.stats = {
            ecs: this.ecs.stats,
            systems: 0,
            plugins: 0,
            systemsStats: {},
        }

        log.i('Gengine started')
    }

    /** Time elapsed since last frame in seconds */
    get timeElapsedS() {
        return this.time.delta
    }

    private tick = () => {
        this.time.startFrame()

        for (const system of this.systems) {
            const systemStart = Clock.now()
            system(this)
            this.stats.systemsStats[system.label].runtime = Math.floor(Clock.now() - systemStart)
        }

        this.updateListeners('endframe')

        this.time.endFrame()

        if (this.isRunning) {
            if (this.frameSync) {
                requestAnimationFrame(this.tick)
            } else {
                setTimeout(this.tick)
            }
        }
    }

    start() {
        if (!this.isRunning) {
            this.isRunning = true
            this.updateListeners('start')
            this.tick()
        }
    }

    stop() {
        if (this.isRunning) {
            this.isRunning = false
            this.updateListeners('stop')
        }
    }

    step() {
        if (!this.isRunning) {
            this.tick()
        }
    }

    addEventListener(eventName: WorldEvent, callback: () => void) {
        this.observers[eventName].push(callback)
    }

    removeEventListener(eventName: WorldEvent, callback: () => void) {
        const observers = this.observers[eventName]
        this.observers[eventName] = observers.filter((c) => c !== callback)
    }

    private updateListeners(eventName: WorldEvent) {
        for (const callback of this.observers[eventName]) {
            callback()
        }
    }

    registerSystem(system: System) {
        this.systems.push(system)

        this.stats.systems = this.systems.length
        this.stats.systemsStats[system.label] = {
            label: system.label,
            runtime: 0,
            extra: {},
        }

        return this
    }

    registerSystems(systems: System[]) {
        systems.forEach((s) => this.registerSystem(s))

        return this
    }

    registerPlugin(plugin: Plugin) {
        this.plugins.set(plugin.name, plugin)

        this.stats.plugins = this.plugins.size

        plugin.init(this)

        return this
    }

    getPlugin<T extends PluginCreator>(pluginCreator: T) {
        return this.plugins.get(pluginCreator.label) as PluginFromPluginCreator<T>
    }
}
