import { Clock } from 'three'

import {
    EntityManager,
    type ECSStatsType,
    type System,
    type Plugin,
    type PluginCreator,
    type PluginFromPluginCreator,
} from 'core'

import { AGG_SIZE_DEFAULT, WORLD_MAX_DELTA_DEFAULT, WORLD_MIN_DELTA_DEFAULT, WorldEvent } from 'definitions'
import { log } from 'utils/log'

type SystemStatsType = {
    /** Provided system label */
    label: string
    /** How long it took to run the system last frame (ms) */
    runtime: number
    /** Exta debug information provided by the system */
    extra: Record<string, string | number | boolean>
}

export type StatsType = {
    /** Game engine frames per second.
     * Browsers will cap this at 60fps.
     */
    fps: number
    fpsAgg: number
    /** How long it takes the engine to process and
     * render a frame in milliseconds. Keep this
     * below 16ms to render at 60fps.
     */
    frameTime: number
    frameTimeAgg: number
    /** Number of frames rendered */
    frames: number
    /** Real-world elapsed time since the first frame in seconds */
    totalRuntime: number
    /** Stats generated by the ECS */
    ecs: ECSStatsType
    aggCounter: number
    aggFpsInter: number
    aggFrameTimeInter: number
    /** Number of registered systems */
    systems: number
    /** Number of registered plugins */
    plugins: number
    /** Array of last frame system stats */
    systemsStats: Record<string, SystemStatsType>
}

export class World {
    /** Set this to cap the time elapsed between frames.
     * This can be useful for when the browser pauses the
     * animation frames when tab is in the background and then
     * the time elapsed is huge when the user comes back.
     * Default is around 50ms. Unit is seconds.
     */
    MAX_DELTA = WORLD_MAX_DELTA_DEFAULT
    MIN_DELTA = WORLD_MIN_DELTA_DEFAULT
    AGG_SIZE = AGG_SIZE_DEFAULT

    private clock = new Clock()
    private delta = 0 // Seconds
    private plugins = new Map<PluginCreator['label'], Plugin>()
    private systems: System[] = []
    private observers: Record<WorldEvent, (() => void)[]> = {
        start: [],
        stop: [],
        endframe: [],
    }

    readonly stats: StatsType
    readonly ecs: EntityManager

    isRunning = false

    frameSync = true

    constructor() {
        this.ecs = new EntityManager()

        this.stats = {
            fps: 0,
            fpsAgg: 0,
            frameTime: 0,
            frameTimeAgg: 0,
            frames: 0,
            totalRuntime: 0,
            ecs: this.ecs.stats,
            aggCounter: 0,
            aggFpsInter: 0,
            aggFrameTimeInter: 0,
            systemsStats: {},
            systems: 0,
            plugins: 0,
        }

        this.addEventListener.bind(this)

        log.i('Gengine started')
    }

    /** Time elapsed since last frame in seconds */
    get timeElapsedS() {
        return this.delta
    }

    private tick() {
        performance.mark('Framestart')
        this.delta = Math.min(Math.max(this.clock.getDelta(), 0.001), this.MAX_DELTA)
        this.stats.fps = Math.floor(1 / this.delta)

        this.systems.forEach((system) => {
            const name = `System: ${system.label}`
            performance.mark(name)
            system(this)
            this.stats.systemsStats[system.label].runtime = Math.floor(
                performance.measure(`${name} finish`, name).duration,
            )
        })

        this.stats.frameTime = Math.floor(performance.measure('Frame length', 'Framestart').duration)
        this.stats.frames += 1
        this.stats.totalRuntime = this.clock.elapsedTime
        this.updateListeners('endframe')

        this.stats.aggCounter += 1
        this.stats.aggFpsInter += this.stats.fps
        this.stats.aggFrameTimeInter += this.stats.frameTime

        if (this.stats.aggCounter >= this.AGG_SIZE) {
            this.stats.fpsAgg = Math.round(this.stats.aggFpsInter / this.AGG_SIZE)
            this.stats.frameTimeAgg = Math.round(this.stats.aggFrameTimeInter / this.AGG_SIZE)
            this.stats.aggCounter = 0
            this.stats.aggFpsInter = 0
            this.stats.aggFrameTimeInter = 0
        }

        if (this.isRunning) {
            if (this.frameSync) {
                requestAnimationFrame(this.tick.bind(this))
            } else {
                setTimeout(this.tick.bind(this))
            }
        }
    }

    start() {
        if (!this.isRunning) {
            this.isRunning = true
            this.updateListeners('start')
            this.tick()
        }
    }

    stop() {
        if (this.isRunning) {
            this.isRunning = false
            this.updateListeners('stop')
        }
    }

    step() {
        if (!this.isRunning) {
            this.tick()
        }
    }

    addEventListener(eventName: WorldEvent, callback: () => void) {
        this.observers[eventName].push(callback)
    }

    removeEventListener(eventName: WorldEvent, callback: () => void) {
        const observers = this.observers[eventName]
        this.observers[eventName] = observers.filter((c) => c !== callback)
    }

    private updateListeners(eventName: WorldEvent) {
        this.observers[eventName].forEach((c) => c())
    }

    registerSystem(system: System) {
        this.systems.push(system)

        this.stats.systems = this.systems.length
        this.stats.systemsStats[system.label] = {
            label: system.label,
            runtime: 0,
            extra: {},
        }

        return this
    }

    registerSystems(systems: System[]) {
        systems.forEach((s) => this.registerSystem(s))

        return this
    }

    registerPlugin(plugin: Plugin) {
        this.plugins.set(plugin.name, plugin)

        this.stats.plugins = this.plugins.size

        plugin.init(this)

        return this
    }

    getPlugin<T extends PluginCreator>(pluginCreator: T) {
        return this.plugins.get(pluginCreator.label) as PluginFromPluginCreator<T>
    }
}
