import { Clock } from 'three'

import { WORLD_MAX_DELTA, WorldEvent } from './constants'

import { ECS, ECSStatsType } from './ecs'

export interface StatsType {
    /** Game engine frames per second.
     * Browsers will cap this at 60fps.
     */
    fps: number
    /** How long it takes the engine to process and
     * render a frame in milliseconds. Keep this
     * below 16ms to render at 60fps.
     */
    frameTime: number
    frames: number
    /** Real-world elapsed time since the first frame in seconds */
    totalRuntime: number
    /** Stats generated by the ECS */
    ecs: ECSStatsType
}

export class World {
    /** Set this to cap the time elapsed between frames.
     * This can be useful for when the browser pauses the
     * animation frames when tab is in the background and then
     * the time elapsed is huge when the user comes back.
     * Default is around 50ms. Unit is seconds.
     */
    MAX_DELTA = WORLD_MAX_DELTA

    private clock = new Clock()
    private delta = 0 // Seconds
    private observers: Record<WorldEvent, Array<() => void | never>> = {
        start: [],
        stop: [],
        endframe: [],
    }

    readonly stats: StatsType
    readonly ecs: ECS

    isRunning = false

    constructor() {
        this.ecs = new ECS()

        this.stats = {
            fps: 0,
            frameTime: 0,
            frames: 0,
            totalRuntime: 0,
            ecs: this.ecs.stats,
        }

        this.addEventListener.bind(this)
    }

    /** Time elapsed since last frame in seconds */
    get timeElapsedS() {
        return this.delta
    }

    private tick() {
        performance.mark('Framestart')
        this.delta = Math.min(this.clock.getDelta(), this.MAX_DELTA)
        this.stats.fps = Math.floor(1 / this.delta)

        this.ecs.tick(this)

        this.stats.frameTime = performance.measure('Frame length', 'Framestart').duration
        this.stats.frames += 1
        this.stats.totalRuntime = this.clock.elapsedTime
        this.updateListeners('endframe')

        if (this.isRunning) {
            requestAnimationFrame(this.tick.bind(this))
        }
    }

    start() {
        if (!this.isRunning) {
            this.isRunning = true
            this.updateListeners('start')
            this.tick()
        }
    }

    stop() {
        if (this.isRunning) {
            this.isRunning = false
            this.updateListeners('stop')
        }
    }

    step() {
        if (!this.isRunning) {
            this.tick()
        }
    }

    addEventListener(eventName: WorldEvent, callback: () => void) {
        this.observers[eventName].push(callback)
    }

    removeEventListener(eventName: WorldEvent, callback: () => void) {
        const observers = this.observers[eventName]
        this.observers[eventName] = observers.filter((c) => c !== callback)
    }

    private updateListeners(eventName: WorldEvent) {
        this.observers[eventName].forEach((c) => c())
    }
}
